headless: true
username: "${USERNAME}"
password: "${PASSWORD}"
have_booking: false
element_timeout: 20000
retries: 4
scrape_refresh_time_min: 120
scraping_enabled: true
parallel_browsers: 4
proxy_path: "${PROXY_PATH}"
webhook_url: "${WEBHOOK_URL}"
